config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'home#index'
  get '/welcome' => 'home#welcome', as: 'welcome'
  get '/future' => 'home#future', as: 'future'
  get '/past' => 'home#past', as: 'past'

  get '/complete_calendar' => 'home#complete_calendar', as: 'complete_calendar'

  patch '/tasks/:id/start' => 'tasks#start', as: "start_task"
  patch '/tasks/:id/complete' => 'tasks#complete', as: "complete_task"
  patch '/tasks/:id/cancel' => 'tasks#cancel', as: "cancel"

  post '/tasks/:id/tb_sub' => 'tasks#time_box_subtract'
  post '/tasks/:id/tb_add' => 'tasks#time_box_add'
  post '/tasks/:id/pr_sub' => 'tasks#priority_subtract'
  post '/tasks/:id/pr_add' => 'tasks#priority_add'

  get '/tasks/:id/start' => 'tasks#start'

  get '/users/alert' => 'users#alert'
  patch '/users/snooze' => 'users#snooze'

  get '/settings' => 'users#edit', as: 'edit_user'
  patch '/settings' => 'users#update', as: 'user'

  resources :sessions, only: [:create, :destroy]
  resources :tasks

  get "*path", to: redirect('/')
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :creator, class_name: "User"
  validates :time_box, :inclusion => { in: 1..1440 }
  validates :priority, :inclusion => { in: 1..3 }
  validates :name, length: { in: 4..140 }
  validate :due_date_validation

  def due_date_validation
    errors.add(:due_date, "can't be in the past") if
      !due_date.blank? and due_date < Date.today
  end

  def target_finish_time
    Time.at(self.start_time).utc + (self.time_box * 60)
  end

  def duration
    if start_time && end_time
      return ((end_time - start_time)/60).to_i
    else
      return 0
    end
  end

  def time_box_difference
    time_box - duration
  end

  def time_box_difference_in_words
    if time_box_difference >= 0
      return "#{time_box_difference} min under"
    else
      return "#{0 - time_box_difference} min over"
    end
  end

  def completed?
    return self.start_time && self.end_time
  end

  def task_in_progress
    self.start_time && !self.end_time
  end

  def time_box_subtract
    self.time_box -= self.creator.default_time_increment
  end

  def time_box_add
    self.time_box += self.creator.default_time_increment
  end

  def priority_subtract
    self.priority += 1
  end

  def priority_add
    self.priority -= 1
  end

  def calendar_event_created?
    self.task_in_progress || self.end_time
  end

  def form_due_date
    return Time.at(self.due_date).strftime("%F") if self.due_date
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @task = Task.new
    @tasks = current_user.pending_tasks.sort_by(&:id).reverse
  end

  def create
    task = Task.new(task_params)
    task.update(creator: current_user)
    redirect_to tasks_path
  end

  def show
    @browser_timezone = browser_timezone
    @task = Task.find_by(id: params[:id])
    if @task && @task.creator == current_user
      if request.xhr?
        render json: @task
      end
    else
      redirect_to root_path
    end
  end

  def start
    task = Task.find_by(id: params[:id])
    if !current_user.current_task
      calendar_event = current_user.begin_task(task)
      task.update(event_id: calendar_event.id, start_time: Time.at(calendar_event.start.dateTime))
    end
    redirect_to root_path
  end

  def complete
    task = Task.find_by(id: params[:id])
    calendar_event = current_user.complete_task(task)
    task.update(event_id: calendar_event.id, end_time: Time.at(calendar_event.end.dateTime))
    redirect_to root_path
  end

  def cancel
    task = Task.find_by(id: params[:id])
    current_user.remove_calendar_event(task)
    task.start_time = nil
    if task.save
      redirect_to root_path
    end
  end

  def edit
    @task = Task.find_by(id: params[:id])
    if request.xhr?
      render partial: "new"
    else
      redirect_to tasks_path
    end
  end

  def destroy
    task = Task.find_by(id: params[:id])
    if task.end_time
      task.destroy
      redirect_to past_path
    else
      task.destroy
      redirect_to tasks_path
    end
  end

  def update
    @task = Task.find_by(id: params[:id])
    @task.update(task_params)
    if @task.calendar_event_created?
      calendar_event = current_user.update_event_description(@task)
      calendar_event.description = @task.description
    end
    if request.xhr?
      render partial: "list_item_header", locals: {task: @task}
    else
      redirect_to tasks_path
    end
  end

  def time_box_subtract
    if request.xhr?
      @task = Task.find_by(id: params[:id])
      @task.time_box_subtract
      @task.save
      render partial: "tasks/timebox_tag", locals: {task: Task.find_by(id: params[:id])}
    end
  end

  def time_box_add
    if request.xhr?
      @task = Task.find_by(id: params[:id])
      @task.time_box_add
      @task.save
      render partial: "tasks/timebox_tag", locals: {task: Task.find_by(id: params[:id])}
    end
  end

  def priority_subtract
    if request.xhr?
      @task = Task.find_by(id: params[:id])
      @task.priority_subtract
      @task.save
      render partial: "tasks/priority_tag", locals: {task: Task.find_by(id: params[:id])}
    end
  end

  def priority_add
    if request.xhr?
      @task = Task.find_by(id: params[:id])
      @task.priority_add
      @task.save
      render partial: "tasks/priority_tag", locals: {task: Task.find_by(id: params[:id])}
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :due_date, :description)
  end

end

app/views/tasks/_alert.html.erb
<div class="alert alert-warning" role="alert">
  <strong>You've got spare time!</strong> Would you like to start <em><%= task.name %></em>? (<%= task.time_box %> minutes)
	<div class="clearfix">
	  <div class="btn-group" role="group">
    <%= link_to "Start Task", {:action => "start", id: "#{task.id}", method: :patch}, class: "btn btn-default", role: "button" %>
	    <div class="btn-group" role="group">
    		<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">Snooze Alerts<span class="caret"></span></button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="snooze">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="30">30 minutes</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="60">1 hour</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="180">3 hours</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="360">6 hours</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="720">12 hours</a></li>
      	</ul>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_calendar.html.erb
<%= form_for task do |f| -%>
  <% f.label :due_date %>
  <%= f.datetime_local_field :due_date, ampm: true, :order => [:month, :day, :year, :hour, :minute] %>
  <%= f.submit %>
<% end %>

app/views/tasks/_due_tag.html.erb
<% case task.due_date %>
<% when nil %>
  <span class="label label-default">N/A</span>
<% else %>
  <span class="label label-default"><%= format_local_date(task.due_date) %></span>
<% end %>

app/views/tasks/_in_progress.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="panel panel-info user-status">
	  <div class="panel-heading">
	    <p>Status: <strong>Task in Progress</strong></p>
	  </div>
		<div class="panel-body">It looks like you're busy with the following Timetris task:</div>
	</div>
</div>

<div class="task-in-progress" id="<%= @task.id %>">

	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		<div class="panel panel-primary calendar">
			<div class="panel-heading"><%= format_local_time_without_date(@next_event.start.dateTime) %> - <%= format_local_time_without_date(@next_event.end.dateTime) %>
			  <a target="_blank" href="https://www.google.com/calendar">
			    <div class="pull-right">
			    <span class="glyphicon glyphicon-calendar"></span></div>
			  </a>
			</div>
		  <div class="panel-body">

		  	<strong><%= @next_event.summary %></strong>

	  		<p class="text-center">
					<span class="hours">00</span>
				  <span class="minutes">: 00</span>
				  <span class="seconds">: 00</span>
				</p>

				<br>

		  	<div class="progress">
				  <div class="progress-ticker progress-bar progress-bar-striped active" role="progressbar">
				    0%
				  </div>
				</div>

				Note:

				<%= render "tasks/note_form" %>

				<div class="btn-group btn-group-justified task-buttons" role="group">
					<div class="btn-group" role="group">
						<%= button_to "I'm Finished", complete_task_path(@task), title: "finish task", method: :patch, class: "btn btn-success left" %>
					</div>
					<div class="btn-group" role="group">
						<%= button_to "Cancel Task", cancel_path(@task), class: "btn btn-danger right", title: "cancel task", method: :patch %>
					</div>
				</div>

		  </div>
		</div>
	</div>

</div>

app/views/tasks/_list_item.html.erb
<div class="panel panel-default task" id="<%= task.id %>">
	<div class="panel-heading">
		<div class="col-xs-12 col-sm-6 col-md-6 name">
			<h5 class="visible-md visible-lg"><%= task.name.truncate(48) %>
				<a href="#" class="task-edit">
					<span class="glyphicon glyphicon-pencil" title="edit title"></span>
				</a>
			</h5>
			<h5 class="visible-sm visible-xs"><%= task.name.truncate(32) %>
				<a href="#" class="task-edit">
					<span class="glyphicon glyphicon-pencil" title="edit title"></span>
				</a>
			</h5>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-6 input-group date form_date">
			<span class="input-group-addon"><span>Due:</span></span>
				<%= form_for task, method: "patch" do |f|%>
				<%= f.date_field :due_date, class: "form-control", title: "edit due date", min: format_datepicker_time(Time.now) %>
			<% end %>
		</div>
	</div>
  <div class="panel-body">
	  <div class="col-xs-12 col-sm-6 col-md-6 option">
  		<div class="col-xs-4 col-sm-4 col-md-4 option">
	  		<h5>Timebox: </h5>
  		</div>
  		<div class="col-xs-8 col-sm-8 col-md-8 option">
  			<h5>
		  		<a href="#" class="timebox-subtract">
						<span class="glyphicon glyphicon-minus-sign" title="decrease timebox"></span>
					</a>
				</h5>
	  		<h4 class="timebox-tag">
	  			<%= render partial: "tasks/timebox_tag", locals: {task: task} %>
	  		</h4>
	  		<h5>
		  		<a href="#" class="timebox-add">
						<span class="glyphicon glyphicon-plus-sign" title="increase timebox"></span>
					</a>
				</h5>
			</div>
	  </div>
	  <div class="col-xs-12 col-sm-6 col-md-6 option">
  		<div class="col-xs-4 col-sm-4 col-md-4 option">
	  		<h5>Priority: </h5>
  		</div>
  		<div class="col-xs-8 col-sm-8 col-md-8 option">
  			<h5>
		  		<a href="#" class="priority-subtract">
						<span class="glyphicon glyphicon-minus-sign" title="decrease priority"></span>
					</a>
				</h5>
	  		<h4 class="priority-tag">
	  			<%= render partial: "tasks/priority_tag", locals: {task: task} %>
	  		</h4>
	  		<h5>
		  		<a href="#" class="priority-add">
						<span class="glyphicon glyphicon-plus-sign" title="increase priority"></span>
					</a>
				</h5>
			</div>
	  </div>
  </div>
	<div class="panel-footer">
	  <div class="btn-group btn-group-justified task-buttons" role="group">
			<div class="btn-group" role="group">
				<%= button_to "Remove Task", task_path(task), class: "btn btn-danger", title: "remove task", method: :delete, data: { confirm: "Are you sure?" } %>
			</div>
		</div>

  </div>
</div>

app/views/tasks/_list_item_header.html.erb
<h5 class="visible-md visible-lg"><%= task.name.truncate(48) %>
	<a href="#" class="task-edit">
		<span class="glyphicon glyphicon-pencil" title="edit title"></span>
	</a>
</h5>
<h5 class="visible-sm visible-xs"><%= task.name.truncate(32) %>
	<a href="#" class="task-edit">
		<span class="glyphicon glyphicon-pencil" title="edit title"></span>
	</a>
</h5>

app/views/tasks/_list_item_read_only.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 name">
	<div class="panel panel-default task" id="<%= task.id %>">
		<div class="panel-heading">
			<div>
				<div class="visible-md visible-lg">
					<%= task.name.truncate(140) %>
					<div class="pull-right">
			    <span class="glyphicon glyphicon-tasks"></span></div>
				</div>
				<div class="visible-sm visible-xs">
					<%= task.name.truncate(76) %>
					<div class="pull-right">
			    <span class="glyphicon glyphicon-tasks"></span></div>
				</div>
			</div>
		</div>
	  <div class="panel-body">
	  	<div class="option">
	  		<div class="col-xs-4 col-sm-4 col-md-4 option">
		  		<h5>Due: </h5>
	  		</div>
	  		<div class="col-xs-8 col-sm-8 col-md-8 option">
		  		<h4 class="timebox-tag">
		  			<%= render partial: "tasks/due_tag", locals: {task: task} %>
		  		</h4>
				</div>
		  </div>
		  <div class="option">
	  		<div class="col-xs-4 col-sm-4 col-md-4 option">
		  		<h5>Timebox: </h5>
	  		</div>
	  		<div class="col-xs-8 col-sm-8 col-md-8 option">
		  		<h4 class="timebox-tag">
		  			<%= render partial: "tasks/timebox_tag", locals: {task: task} %>
		  		</h4>
				</div>
		  </div>
		  <div class="option">
	  		<div class="col-xs-4 col-sm-4 col-md-4 option">
		  		<h5>Priority: </h5>
	  		</div>
	  		<div class="col-xs-8 col-sm-8 col-md-8 option">
		  		<h4 class="priority-tag">
		  			<%= render partial: "tasks/priority_tag", locals: {task: task} %>
		  		</h4>
				</div>
		  </div>
	  </div>
		<div class="panel-footer">
		  <div class="btn-group btn-group-justified task-buttons" role="group" aria-label="...">
		  	<div class="btn-group" role="group">
					<%= button_to "Start Task", start_task_path(task), class: "btn btn-primary", title: "start task", method: :patch %>
				</div>
			</div>

	  </div>
	</div>
</div>

app/views/tasks/_new.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 name input-group">
	<%= form_for @task, :url => tasks_path, :html => {class: "form-inline task-name-form"} do |f| %>
	  <%= f.text_field :name, class: "form-control", placeholder: "Enter a new task", minlength: "4", maxlength: "140", required: true, autofocus: true %>
	  <span class="input-group-btn">
		  <%= f.submit class: "btn btn-default", title: "create task" %>
	  </span>
	<% end %>
</div>

app/views/tasks/_note_form.html.erb
<div class="note-form">
	<%= form_for @task do |f| %>
	  <%= f.text_area :description, cols: 50, rows: "4", class: "form-control" %>
	  <%= f.submit "Save Note", class: "btn btn-primary", title: "save note" %>
	<% end %>
</div>

app/views/tasks/_priority_tag.html.erb
<% case task.priority %>
<% when 1 %>
  <span class="label label-danger">High</span>
<% when 2 %>
  <span class="label label-warning">Medium</span>
<% when 3 %>
  <span class="label label-success">Low</span>
<% end %>

app/views/tasks/_timebox_tag.html.erb
<span class="label label-primary"><span class="time-box"><%= task.time_box %></span> min</span>

app/views/tasks/index.html.erb
<div class="jumbotron">

	<h2>Manage Tasks</h2>

	<%= render partial: "tasks/new" %>

	<br>

	<% if @tasks.any? %>
	  <% @tasks.each do |task| %>
	    <%= render partial: "tasks/list_item", locals: {task: task} %>
	  <% end %>
	<% else %>
	<ul class="list-group">
		<li class="list-group-item task">
	  	<h4 class="list-group-item-heading">You don't have any tasks.</h4>
		</li>
	</ul>
	<% end %>

</div>

app/views/tasks/show.html.erb
<div class="jumbotron">

	<div class="container">
		<div class="col-xs-12 col-sm-12 col-md-12">

			<% if @task.completed? %>
				<div class="panel panel-primary calendar">
			<% else %>
				<div class="panel panel-default">
			<% end %>


				<div class="panel-heading">

					<% if @task.completed? %>
						<%= format_local_date(@task.start_time) %>
					<% else %>
						Task Pending
					<% end %>
			    <div class="pull-right">
			    <span class="glyphicon glyphicon-tasks"></span></div>
				</div>
			  <div class="panel-body">

			  	<p><strong><%= @task.name %></strong></p>

					<% if @task.completed? %>

						<div class="col-md-4 col-sm-4 col-xs-12 report-panel">
						  <div class="panel panel-default">
						    <div class="panel-heading">
						      <h5>Started at</h5>
						    </div>
						    <div class="panel-body">
						      <%= format_local_time_without_date(@task.start_time) %>
						    </div>
						  </div>
						</div>

						<div class="col-md-4 col-sm-4 col-xs-12 report-panel">
						  <div class="panel panel-default">
						    <div class="panel-heading">
						     <h5>Ended at</h5>
						    </div>
						    <div class="panel-body">
						      <%= format_local_time_without_date(@task.end_time) %>
						    </div>
						  </div>
						</div>

						<div class="col-md-4 col-sm-4 col-xs-12 report-panel">
						  <div class="panel panel-default">
						    <div class="panel-heading">
						      <h5>Timebox Diff.</h5>
						    </div>
						    <div class="panel-body">
						      <%= @task.time_box_difference_in_words %>
						    </div>
						  </div>
						</div>

					<% end %>

						<div>Note:</div>

						<%= render "tasks/note_form" %>

						<div class="btn-group btn-group-justified task-buttons" role="group">
							<div class="btn-group" role="group">
								<%= button_to "Remove Task", task_path(@task), class: "btn btn-danger", title: "remove task", method: :delete, data: { confirm: "Are you sure?" } %>
							</div>
						</div>

				  </div>
				</div>
			</div>
		</div>

	</div>