config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'home#index'
  get '/welcome' => 'home#welcome', as: 'welcome'
  get '/future' => 'home#future', as: 'future'
  get '/past' => 'home#past', as: 'past'

  get '/complete_calendar' => 'home#complete_calendar', as: 'complete_calendar'

  patch '/tasks/:id/start' => 'tasks#start', as: "start_task"
  patch '/tasks/:id/complete' => 'tasks#complete', as: "complete_task"
  patch '/tasks/:id/cancel' => 'tasks#cancel', as: "cancel"

  post '/tasks/:id/tb_sub' => 'tasks#time_box_subtract'
  post '/tasks/:id/tb_add' => 'tasks#time_box_add'
  post '/tasks/:id/pr_sub' => 'tasks#priority_subtract'
  post '/tasks/:id/pr_add' => 'tasks#priority_add'

  get '/tasks/:id/start' => 'tasks#start'

  get '/users/alert' => 'users#alert'
  patch '/users/snooze' => 'users#snooze'

  get '/settings' => 'users#edit', as: 'edit_user'
  patch '/settings' => 'users#update', as: 'user'

  resources :sessions, only: [:create, :destroy]
  resources :tasks

  get "*path", to: redirect('/')
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: [:welcome]

  def index
    @upcoming_events = current_user.upcoming_events
    @task = current_user.current_task
    @time_to_next_event = current_user.time_to_next_event(@upcoming_events)
    @next_event = @upcoming_events.first
    @tasks = current_user.possible_tasks(@upcoming_events)
  end

  def past
    @tasks = current_user.completed_tasks
    @time_box = current_user.total_time_box
    @task_time = current_user.total_task_time
    @avg_difference = current_user.average_difference
  end

  def welcome
  end

  def complete_calendar
    upcoming_events = current_user.upcoming_events
    current_user.complete_calendar_event(upcoming_events.first)
    redirect_to root_path
  end

  def future
    @upcoming_events = current_user.upcoming_events
    google_events = []
    @upcoming_events.each{ |event| google_events << [event, event.start.dateTime.to_i] }

    predicted_events = current_user.predict_tasks(current_user.find_the_gaps(current_user.sort_upcoming_events(@upcoming_events)))
    @events = google_events + predicted_events
    @events.sort_by!{ |e| e[1] }
  end

end

app/views/home/_calendar_event.html.erb
<div class="col-xs-12 col-sm-6 col-md-6">
	<div class="panel panel-primary calendar">
		<div class="panel-heading"><%= format_local_time_without_date(@next_event.start.dateTime) %> - <%= format_local_time_without_date(@next_event.end.dateTime) %>
		  <a target="_blank" href="https://www.google.com/calendar">
		    <div class="pull-right">
		    <span class="glyphicon glyphicon-calendar"></span></div>
		  </a>
		</div>
	  <div class="panel-body"><%= @next_event.summary %></div>
	</div>
</div>

app/views/home/_task_row.html.erb
<td class="col-md-3"><%= link_to "#{task.name}", task %></td>
<td class="col-md-3"><%= task.time_box %> min</td>
<% if task.due_date %>
  <td class="col-md-3"><%= format_local_time(task.due_date) %></td>
<% else %>
  <td class="col-md-3">N/A</td>
<% end %>
<td class="col-md-3"><%= format_priority(task) %></td>

app/views/home/autocal.html.erb
<!-- change this to if jumboarray.any? to test the changes, read home_controller for more info -->
<% if @jumboarray.any? %>
  <% @jumboarray.each do |event| %>
  <% if event[0] == :google %>
    <li class="list-group-item" style="background-color:lightblue"> GOOGLE EVENT:
  <% else %>
    <li class="list-group-item" style="background-color:lightyellow">
  <% end %>
    <%= format_local_time(event[1]) %>
    <% if event[2] == nil %>
      No Event Title
    <% else %>
      <%= event[2] %>
    <% end %>
    <br>
  <% end %>
  </li>
  <% else %>
    <h1>FOOL! You have no Google Calendar events or Timetris tasks!</h1>
<% end %>

app/views/home/completed.html.erb
<div class="jumbotron">

  <% if @tasks %>

    <table>
      <tr>
        <%= render 'tasks/headers' %>
      </tr>
      <% @tasks.each do |task| %>
        <tr>
          <%= render partial: "home/task_row", locals: {task: task} %>
          <td><%= button_to "Remove Task", task_path(task), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </table>

  <% else %>

    Go Complete Some Tasks!

  <% end %>

</div>

app/views/home/future.html.erb
<meta http-equiv="refresh" content="60">

<div class="jumbotron">

  <% if @events.any? %>

  <h2>Upcoming Events</h2>

  <% @events.each do |e| %>
    <% event = e.first %>

    <% if event.class == Google::APIClient::Schema::Calendar::V3::Event  %>
      <div class="panel panel-primary calendar">
    <% else %>
      <div class="panel panel-default">
    <% end %>

        <div class="panel-heading"><%= format_local_time_without_date(event.start.dateTime) %> - <%= format_local_time_without_date(event.end.dateTime) %>
        <% if event.class == Google::APIClient::Schema::Calendar::V3::Event  %>
          <a target="_blank" href="https://www.google.com/calendar">
            <div class="pull-right">Google Calendar
            <span class="glyphicon glyphicon-calendar"></span></div>
          </a>
        <% else %>
          <div class="pull-right">Proposed Task <span class="glyphicon glyphicon-tasks"></span></div>
        <% end %>

        </div>

        <% if event.summary == nil %>
          <div class="panel-body">No Event Title</div>
        <% else %>
          <div class="panel-body"><%= event.summary %></div>
        <% end %>
      </div>

  <% end %>

<% else %>

  <h2>Your future is uncertain...</h2>
  <p>You have no upcoming Google Calendar events or Timetris tasks to complete. Add tasks by clicking on the "Manage Tasks" tab!</p>

<% end %>

app/views/home/index.html.erb
<div class="jumbotron">

	<div class="container">

	<% if @task %>
		<%= render "tasks/in_progress" %>
	<% else %>
		<meta http-equiv="refresh" content="60">

		<% if @time_to_next_event > 0 %>
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<div class="panel panel-success user-status">
				  <div class="panel-heading">
				    <p>Status: <strong>Free</strong></p>
				  </div>

					<% if @time_to_next_event >= 1440 %>
						<div class="panel-body">Relax! You have no more events today.
					<% else %>
						<div class="panel-body">You have <strong><%= time_ago_in_words(@time_to_next_event.minutes.from_now) %></strong> until your next event.
					<% end %>

					<% if @tasks.any? %>
						Here are some tasks to complete:</div>
					<% elsif current_user.pending_tasks.any? %>
						You don't have enough time to complete any tasks.  Perhaps later?</div>
					<% else %>
						You don't have any tasks on your list.  You can add tasks from the "Manage Tasks" tab.</div>
					<% end %>
				</div>
			</div>

			<% if @tasks.any? %>
			  <% @tasks.each do |task| %>
			      <%= render partial: "tasks/list_item_read_only", locals: {task: task} %>
			  <% end %>
			<% end %>

		<% else %>

		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="panel panel-danger user-status">
			  <div class="panel-heading">
			    <p>Status: <strong>Busy</strong></p>
			  </div>
				<div class="panel-body">It looks like you're busy with the following event:</div>
			</div>
		</div>

		<%= render "calendar_event" %>

		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
		  <h4>We'll let you get back to it!</h4>
		  <h5>Finished early?  <%= link_to "Click here", complete_calendar_path %> to end your event and find a task from your list!</h5>
	  </div>
		<% end %>
	<% end %>

</div>

app/views/home/past.html.erb
<div class="jumbotron">

  <% if @tasks.any? %>

    <div class="col-md-12 col-sm-12 col-xs-12 panel panel-default report-panel">
      <div class="panel-body">
        <p>On average you completed your tasks <strong><%= current_user.average_difference_in_words %></strong> your timebox.</p>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12 report-panel">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h5>Total Tasks</h5>
        </div>
        <div class="panel-body">
          <%= @tasks.count %> completed
        </div>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12 report-panel">
      <div class="panel panel-default">
        <div class="panel-heading">
         <h5>Total Task Time</h5>
        </div>
        <div class="panel-body">
          <%= @task_time %> min
        </div>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12 report-panel">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h5>Total Timebox</h5>
        </div>
        <div class="panel-body">
          <%= @time_box %> min
        </div>
      </div>
    </div>


    <table class="table table-striped">
      <tr>
        <th class="col-md-1">Date</th>
        <th class="col-md-1">Task Name</th>
        <th class="col-md-1 visible-md visible-lg">Timebox</th>
        <th class="col-md-1 visible-md visible-lg">Task Time</th>
        <th class="col-md-1">Timebox Difference</th>
      </tr>

      <% @tasks.each do |task| %>
        <tr>
          <td class="col-md-1"><%= format_report_time(task.start_time) %></td>
          <td class="col-md-1"><%= link_to "#{task.name}", task %></td>
          <td class="col-md-1 visible-md visible-lg"><%= task.time_box %> min</td>
          <td class="col-md-1 visible-md visible-lg"><%= task.duration %> min</td>
          <td class="col-md-1"><%= task.time_box_difference_in_words %></td>
        </tr>
      <% end %>

    </table>

  <% else %>
    <h2>What is a past without tasks?</h2>
    <p>You have no completed tasks, so there's not much to see here yet.  Try checking back after you've completed some tasks to see a summary!</p>
  <% end %>

</div>

app/views/home/pending.html.erb
<h2>Pending Tasks</h2>

<%= render partial: "tasks/new" %>

<br>

<% if @tasks.any? %>
  <% @tasks.each do |task| %>
    <%= render partial: "tasks/list_item", locals: {task: task} %>
  <% end %>
<% else %>
<ul class="list-group">
	<li class="list-group-item task">
  	<h4 class="list-group-item-heading">It looks like you don't have any pending tasks!</h4>
	</li>
</ul>
<% end %>

app/views/home/reports.html.erb
<div class="col-md-12 col-sm-12 col-xs-12 panel panel-default report-panel">
  <div class="panel-body">
    <p>On average you completed your tasks <strong><%= current_user.average_difference_in_words %></strong> your timebox.</p>
  </div>
</div>

<div class="col-md-4 col-sm-4 col-xs-12 report-panel">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h5>Total Tasks</h5>
    </div>
    <div class="panel-body">
      <%= @count %> completed
    </div>
  </div>
</div>

<div class="col-md-4 col-sm-4 col-xs-12 report-panel">
  <div class="panel panel-default">
    <div class="panel-heading">
     <h5>Total Task Time</h5>
    </div>
    <div class="panel-body">
      <%= @task_time %> min
    </div>
  </div>
</div>

<div class="col-md-4 col-sm-4 col-xs-12 report-panel">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h5>Total Timebox</h5>
    </div>
    <div class="panel-body">
      <%= @time_box %> min
    </div>
  </div>
</div>


<table class="table table-striped">
  <tr>
    <th class="col-md-1">Date</th>
    <th class="col-md-1">Task Name</th>
    <th class="col-md-1 visible-md visible-lg">Timebox</th>
    <th class="col-md-1 visible-md visible-lg">Task Time</th>
    <th class="col-md-1">Timebox Difference</th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td class="col-md-1"><%= format_report_time(task.start_time) %></td>
      <td class="col-md-1"><%= link_to "#{task.name}", task %></td>
      <td class="col-md-1 visible-md visible-lg"><%= task.time_box %> min</td>
      <td class="col-md-1 visible-md visible-lg"><%= task.duration %> min</td>
      <td class="col-md-1"><%= task.time_box_difference_in_words %></td>
    </tr>
  <% end %>

</table>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/home/welcome.html.erb
<div class="jumbotron welcome">

  <div class="col-md-12 col-sm-12">
    <h2>Timetris is an app designed to optimize your productivity.</h2>
    <p>Timetris connects with your Google Calendar to fill gaps in your daily schedule.</p>
  </div>

  <div class="container">

    <div class="col-md-4 col-sm-4 col-xs-12 report-panel">
      <div class="panel panel-primary">
        <div class="panel-heading">
         <h5>Present</h5>
        </div>
        <div class="panel-body">
          Start tasks and add them to your Google calendar
        </div>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12 report-panel">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h5>Future</h5>
        </div>
        <div class="panel-body">
          Preview a recommended schedule for the day
        </div>
      </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12 report-panel">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h5>Past</h5>
        </div>
        <div class="panel-body">
          Review completed tasks and track statistics
        </div>
      </div>
    </div>

  </div>

  <br>

  <div class="col-md-12 col-sm-12">
    <p><%= link_to image_tag("gplus.png", :border => 0), "/auth/google_oauth2", :class => 'google-signin' %></p>
  </div>


</div>