config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  root 'home#index'
  get '/welcome' => 'home#welcome', as: 'welcome'
  get '/future' => 'home#future', as: 'future'
  get '/past' => 'home#past', as: 'past'

  get '/complete_calendar' => 'home#complete_calendar', as: 'complete_calendar'

  patch '/tasks/:id/start' => 'tasks#start', as: "start_task"
  patch '/tasks/:id/complete' => 'tasks#complete', as: "complete_task"
  patch '/tasks/:id/cancel' => 'tasks#cancel', as: "cancel"

  post '/tasks/:id/tb_sub' => 'tasks#time_box_subtract'
  post '/tasks/:id/tb_add' => 'tasks#time_box_add'
  post '/tasks/:id/pr_sub' => 'tasks#priority_subtract'
  post '/tasks/:id/pr_add' => 'tasks#priority_add'

  get '/tasks/:id/start' => 'tasks#start'

  get '/users/alert' => 'users#alert'
  patch '/users/snooze' => 'users#snooze'

  get '/settings' => 'users#edit', as: 'edit_user'
  patch '/settings' => 'users#update', as: 'user'

  resources :sessions, only: [:create, :destroy]
  resources :tasks

  get "*path", to: redirect('/')
end

app/views/layouts/_alert.html.erb
<div class="alert alert-warning" role="alert">
  <strong>You've got spare time!</strong> Would you like to start <em><%= @task.name %></em>? (<%= @task.time_box %> minutes)
	<div class="clearfix">
	  <div class="btn-group" role="group">
    <%= link_to "Start Task", {:action => "start", id: "#{@task.id}", method: :patch}, class: "btn btn-default", role: "button" %>
	    <div class="btn-group" role="group">
    		<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">Snooze Alerts<span class="caret"></span></button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="snooze">
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="30">30 minutes</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="60">1 hour</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="180">3 hours</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="360">6 hours</a></li>
          <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="snooze" minutes="720">12 hours</a></li>
      	</ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_calendar_sidebar.html.erb
<div class="container cal-container col-md-4 col-xs-12">
  <div class="panel panel-primary calendar-sidebar">
		<div class="panel-heading">Calendar<span class="glyphicon glyphicon-calendar pull-right"></span></div>
	  <div class="panel-body">
	  	<table class="table">
	  		<% @calendar.each do |row| %>
		  		<tr>
					 	<% row.each do |event| %>
					 		<td><%= event %></td>
					 	<% end %>
				  </tr>
	  		<% end %>
			</table>
	  </div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default main-nav">
  <div class="container-fluid">

    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Timetris</a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav" role="tablist">
        <% if current_user %>
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Present", root_path %></li>
          <li class="<%= 'active' if current_page?(future_path) %>"><%= link_to "Future", future_path %></li>
          <li class="<%= 'active' if current_page?(past_path) %>"><%= link_to "Past", past_path %></li>
        <% else %>
          <li class="<%= 'active' if current_page?(welcome_path) %>"><%= link_to "Welcome", root_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
          <li class="<%= 'active' if current_page?(tasks_path) %>"><%= link_to "Manage Tasks", tasks_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a target="_blank" href="https://www.google.com/calendar/">Google Calendar</a></li>
              <li><a target="_blank" href="https://docs.google.com/forms/d/1PNhgfo13lDBA7bPfKr-t_FfeZ1zKN8xjrJRgJKDcxDk/viewform?usp=send_form">Feedback</a></li>
              <li><a href="<%= edit_user_path %>">Settings</a></li>
              <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
            </ul>
          </li>

        <% else %>

            <li><%= link_to "Sign in with Google+", "/auth/google_oauth2", id: "sign_in" %></li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
  <meta name="author" content="">
  <title>Timetris</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
  <div class="container">
    <%= render partial: "layouts/navbar" %>
    <div class="notification"></div>
    <%= yield %>
  </div>
</body>
</html>